export const FAILED_REQUEST = "AUTH_FAILED_REQUEST";
export const LOADING_REQUEST = "AUTH_LOADING_REQUEST";
export const AUTH_UPDATE_LOADING = "AUTH_UPDATE_LOADING";
export const LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
