export const ADD_EXPORTER = "ADD_EXPORTER";
export const ADD_IMPORTER = "ADD_IMPORTER";
export const ADD_ORDER = "ADD_ORDER";

export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_IMPORTER = "UPDATE_ORDER_IMPORTER";
export const UPDATE_ORDER_EXPORTER = "UPDATE_ORDER_EXPORTER";

export const CLEAR_STATE = "CLEAR_STATE";
export const RESET_LOADING = "RESET_LOADING";
export const SET_LOADING = "SET_LOADING";

export const ADD_SHIPPING = "ADD_SHIPPING";
export const ADD_FINANCE = "ADD_FINANCE";
export const ADD_CONTAINER = "ADD_CONTAINER";
