export const SELECT_TYPE = {
  IMPORT: "IMPORT",
  GOOD: "GOOD",
  SPEC: "SPEC",
  PACKER: "PACKER",
  SAMPLE: "SAMPLE",
  NEW_TYPE: "NEW_TYPE",
};

export const MODAL_TYPE = {
  SALES: "SALES",
  PACKING: "PACKING",
  COMERCIAL: "COMERCIAL",
  OCR: "OCR",
};
